// Markdown report builder for a completed investigation. Pure and shared by
// the browser (one-click export) and testable on the server side.

export function buildReportMarkdown(result, { trace = [], mode = 'live', generatedAt = new Date().toISOString() } = {}) {
  if (!result || typeof result !== 'object') throw new TypeError('result is required');
  const lines = [];
  const percent = Math.round((result.confidence ?? 0) * 100);

  lines.push(`# CineOps investigation report — ${result.incidentId ?? 'unknown incident'}`);
  lines.push('');
  lines.push(`- **Generated:** ${generatedAt} (${mode} mode)`);
  if (result.investigationRef) lines.push(`- **Investigation ref:** ${result.investigationRef}`);
  lines.push(`- **Operator query:** ${result.query ?? '—'}`);
  lines.push(`- **Verdict:** ${result.status ?? 'unknown'} · severity **${result.severity ?? 'unknown'}** · confidence **${percent}%**`);
  lines.push('');
  lines.push('## Root cause');
  lines.push('');
  lines.push(`**${result.rootCause?.stage ?? 'unknown'}** — ${result.rootCause?.finding ?? 'unknown finding'}`);
  lines.push('');
  lines.push('## Recovery decision');
  lines.push('');
  lines.push(result.decision ?? '—');
  lines.push('');
  if (Array.isArray(result.actions) && result.actions.length) {
    lines.push('## Actions');
    lines.push('');
    result.actions.forEach((action, index) => lines.push(`${index + 1}. ${action}`));
    lines.push('');
  }
  if (result.reasoning) {
    lines.push('## Why this verdict');
    lines.push('');
    lines.push(result.reasoning);
    lines.push('');
  }
  if (Array.isArray(result.evidence) && result.evidence.length) {
    lines.push('## Evidence');
    lines.push('');
    lines.push('| # | Signal | Stage | Source | Value | Query |');
    lines.push('| --- | --- | --- | --- | --- | --- |');
    result.evidence.forEach((item, index) => {
      const value = `${item.value}${item.unit === '%' ? '%' : ` ${item.unit ?? ''}`}`.trim();
      const query = item.url ? `[${item.query}](${item.url})` : item.query ?? '';
      lines.push(`| ${index + 1} | ${item.label ?? item.id} | ${item.stage ?? ''} | ${item.source ?? ''} | ${value} | ${query} |`);
    });
    lines.push('');
  }
  if (Array.isArray(result.toolCalls) && result.toolCalls.length) {
    lines.push('## Tool trace');
    lines.push('');
    result.toolCalls.forEach((call, index) => {
      lines.push(`${index + 1}. \`${call.tool}\` — ${call.purpose ?? ''}${call.replay === false ? ' *(live)*' : ' *(replay)*'}`);
    });
    lines.push('');
  }
  if (trace.length) {
    lines.push('## Agent timeline');
    lines.push('');
    trace.forEach((entry) => lines.push(`- \`${entry.time ?? ''}\` **${entry.kind}** ${entry.text}`));
    lines.push('');
  }
  if (result.pipeline) {
    const p = result.pipeline;
    lines.push(`## Pipeline at investigation time: ${p.healthy ?? 0} healthy · ${p.degraded ?? 0} degraded · ${p.failed ?? 0} failed · ${p.waiting ?? 0} waiting`);
    lines.push('');
  }
  lines.push('---');
  lines.push('');
  lines.push('Generated by [CineOps Agent](https://github.com/wenn-id/cineops-agent) — incident investigation for media pipelines.');
  return lines.join('\n');
}
