export const scenarios = {
  'premiere-night': {
    id: 'INC-042',
    hook: 'Save premiere.',
    defaultQuery: 'Can we still make the 21:00 premiere? Find the root cause and safest recovery path.',
    title: 'Premiere delivery blocked',
    production: 'Neon Harbor — Episode 06',
    startedAt: '20:12 UTC',
    replayAt: '20:24 UTC',
    deadline: '21:00 UTC',
    replayWindowSec: 36 * 60,
    stages: [
      { id: 'upload', label: 'Upload', status: 'healthy', detail: 'Master received · 412\u00a0GB' },
      { id: 'ingest', label: 'Ingest', status: 'healthy', detail: 'Checksums verified' },
      { id: 'transcode', label: 'Transcode', status: 'failed', detail: 'H.265 jobs timing out' },
      { id: 'subtitles', label: 'Subtitles', status: 'degraded', detail: '2.4 min behind video' },
      { id: 'quality-control', label: 'Quality control', status: 'waiting', detail: 'Blocked by transcode' },
      { id: 'publish', label: 'Publish', status: 'healthy', detail: 'Release window reserved' },
    ],
    signals: [
      {
        id: 'queue-depth',
        stage: 'transcode',
        source: 'Prometheus',
        label: 'Transcode queue depth',
        value: 186,
        unit: 'jobs',
        baseline: 24,
        score: 100,
        finding: 'Queue is 7.8× baseline and still rising.',
        query: 'max(cineops_transcode_queue_depth)',
      },
      {
        id: 'gpu-utilization',
        stage: 'transcode',
        source: 'Prometheus',
        label: 'GPU worker utilization',
        value: 99.1,
        unit: '%',
        baseline: 72,
        score: 96,
        finding: 'Every GPU worker is saturated; no spare capacity remains.',
        query: 'avg(cineops_gpu_utilization_percent)',
      },
      {
        id: 'error-rate',
        stage: 'transcode',
        source: 'Loki',
        label: 'Encoder timeout rate',
        value: 37.4,
        unit: '%',
        baseline: 1.2,
        score: 92,
        finding: 'Timeout burst began after the 4K HEVC job batch entered the queue.',
        query: '{service="transcoder"} |= "deadline exceeded"',
      },
      {
        id: 'subtitle-lag',
        stage: 'subtitles',
        source: 'Prometheus',
        label: 'Subtitle processing lag',
        value: 2.4,
        unit: 'min',
        baseline: 1,
        score: 38,
        finding: 'Subtitle lag is secondary and does not block recovery.',
        query: 'max(cineops_subtitle_lag_minutes)',
      },
    ],
    toolCalls: [
      { tool: 'query_prometheus', purpose: 'Rank queue, GPU, and lag anomalies' },
      { tool: 'query_loki_logs', purpose: 'Correlate encoder timeout burst' },
      { tool: 'search_dashboards', purpose: 'Locate production runbook context' },
    ],
    playbooks: {
      transcode: {
        decision: 'Premiere is at risk. Pause non-premiere 4K jobs and drain the priority queue before 20:32 UTC.',
        actions: [
          'Pause non-premiere 4K HEVC jobs.',
          'Route priority transcodes to the recovery pool.',
          'Resume quality control when queue depth falls below 40 jobs.',
        ]
      },
      subtitles: {
        decision: 'Subtitle delay detected. Escalate rendering and notify ingest team.',
        actions: [
          'Scale subtitle worker nodes.',
          'Restart hanging subtitle pods.'
        ]
      }
    },
  },

  'storage-surge': {
    id: 'INC-043',
    hook: 'Save the archive drop.',
    defaultQuery: 'Hot tier is nearly full. What is at risk for the archive drop, and how do we free capacity fast?',
    title: 'Ingest storage full during archive drop',
    production: 'Desert Frequency — S02E11',
    startedAt: '09:03 UTC',
    replayAt: '09:15 UTC',
    deadline: '10:00 UTC',
    replayWindowSec: 45 * 60,
    stages: [
      { id: 'upload', label: 'Upload', status: 'healthy', detail: 'Studio drop in progress · 1.2 TB/day' },
      { id: 'ingest', label: 'Ingest', status: 'failed', detail: 'Writes stalling on hot tier' },
      { id: 'transcode', label: 'Transcode', status: 'healthy', detail: 'Proxy renders nominal' },
      { id: 'subtitles', label: 'Subtitles', status: 'healthy', detail: 'ASR pipeline clear' },
      { id: 'quality-control', label: 'Quality control', status: 'waiting', detail: 'Blocked by ingest backlog' },
      { id: 'publish', label: 'Publish', status: 'healthy', detail: 'Season page unchanged' },
    ],
    signals: [
      {
        id: 'hot-tier-usage',
        stage: 'ingest',
        source: 'Prometheus',
        label: 'Hot-tier capacity used',
        value: 98.7,
        unit: '%',
        baseline: 61,
        score: 100,
        finding: 'Hot tier is at 98.7% — writes are one bad batch away from failing outright.',
        query: 'max(cineops_storage_hot_tier_used_percent)',
      },
      {
        id: 'write-latency',
        stage: 'ingest',
        source: 'Prometheus',
        label: 'Ingest write latency',
        value: 842,
        unit: 'ms',
        baseline: 95,
        score: 96,
        finding: 'Write latency is 8.9× baseline as the tier throttles to protect itself.',
        query: 'avg(cineops_ingest_write_latency_ms)',
      },
      {
        id: 'tier-errors',
        stage: 'ingest',
        source: 'Loki',
        label: 'No-space errors',
        value: 14.2,
        unit: '%',
        baseline: 0.1,
        score: 92,
        finding: 'ENOSPC bursts began when the overnight archive drop landed on the hot tier.',
        query: '{service="ingest"} |= "no space left on device"',
      },
      {
        id: 'proxy-renders',
        stage: 'transcode',
        source: 'Prometheus',
        label: 'Proxy render rate',
        value: 118,
        unit: 'jobs/h',
        baseline: 120,
        score: 34,
        finding: 'Proxy rendering is unaffected — the problem is isolated to storage intake.',
        query: 'sum(rate(cineops_proxy_renders[5m])) * 3600',
      },
    ],
    toolCalls: [
      { tool: 'query_prometheus', purpose: 'Rank hot-tier usage and write latency' },
      { tool: 'query_loki_logs', purpose: 'Confirm ENOSPC error bursts' },
      { tool: 'search_dashboards', purpose: 'Find storage capacity runbooks' },
    ],
    playbooks: {
      ingest: {
        decision: 'Hot tier is nearly full. Divert the archive drop to cold storage and evict proxies older than 30 days.',
        actions: [
          'Redirect archive-drop writes to the cold tier.',
          'Evict proxy media older than 30 days from the hot tier.',
          'Resume quality control once hot-tier usage is below 80%.',
        ]
      },
    },
  },

  'subtitle-drift': {
    id: 'INC-044',
    hook: 'Save localization.',
    defaultQuery: 'Why are the subtitles drifting, and can we still ship the localization on time?',
    title: 'Subtitle drift on live localization',
    production: 'Harbor Lights — Finale',
    startedAt: '18:40 UTC',
    replayAt: '18:52 UTC',
    deadline: '19:30 UTC',
    replayWindowSec: 40 * 60,
    stages: [
      { id: 'upload', label: 'Upload', status: 'healthy', detail: 'Master received · 96 GB' },
      { id: 'ingest', label: 'Ingest', status: 'healthy', detail: 'Checksums verified' },
      { id: 'transcode', label: 'Transcode', status: 'healthy', detail: 'All ladders rendered' },
      { id: 'subtitles', label: 'Subtitles', status: 'failed', detail: 'Timings drifting on 4 locales' },
      { id: 'quality-control', label: 'Quality control', status: 'waiting', detail: 'Blocked by subtitle QC' },
      { id: 'publish', label: 'Publish', status: 'healthy', detail: 'Localization window open' },
    ],
    signals: [
      {
        id: 'drift-minutes',
        stage: 'subtitles',
        source: 'Prometheus',
        label: 'Subtitle drift',
        value: 4.8,
        unit: 'min',
        baseline: 0.4,
        score: 100,
        finding: 'Drift is 4.8 minutes and compounding across all four localization tracks.',
        query: 'max(cineops_subtitle_drift_minutes)',
      },
      {
        id: 'asr-queue',
        stage: 'subtitles',
        source: 'Prometheus',
        label: 'ASR resegment queue',
        value: 312,
        unit: 'segments',
        baseline: 18,
        score: 95,
        finding: 'Resegmentation is re-queued 17× baseline after the audio timecode reset.',
        query: 'max(cineops_asr_resegment_queue)',
      },
      {
        id: 'alignment-errors',
        stage: 'subtitles',
        source: 'Loki',
        label: 'Alignment failures',
        value: 9.6,
        unit: '%',
        baseline: 0.4,
        score: 91,
        finding: 'Forced alignment fails on segments after the mid-episode timecode reset.',
        query: '{service="subtitles"} |= "alignment failed"',
      },
      {
        id: 'render-ladder',
        stage: 'transcode',
        source: 'Prometheus',
        label: 'Ladder render rate',
        value: 240,
        unit: 'jobs/h',
        baseline: 238,
        score: 30,
        finding: 'Video rendering is healthy — drift is confined to the localization track.',
        query: 'sum(rate(cineops_ladder_renders[5m])) * 3600',
      },
    ],
    toolCalls: [
      { tool: 'query_prometheus', purpose: 'Rank drift and resegment queue depth' },
      { tool: 'query_loki_logs', purpose: 'Correlate alignment failures' },
      { tool: 'search_dashboards', purpose: 'Locate localization runbook' },
    ],
    playbooks: {
      subtitles: {
        decision: 'Timecode reset broke alignment. Re-anchor with forced alignment from the 42-minute mark before the localization window closes.',
        actions: [
          'Re-run forced alignment anchored at the 42-minute timecode reset.',
          'Freeze publication of the four affected localization tracks.',
          'Resume quality control once drift falls below 30 seconds.',
        ]
      },
    },
  },

  'cdn-origin-storm': {
    id: 'INC-045',
    hook: 'Save publishing.',
    defaultQuery: 'Publishing is failing at the CDN. What is failing and how do we stabilize it?',
    title: 'Publish failing on CDN origin errors',
    production: 'Midnight Circuit — Episode 02',
    startedAt: '21:05 UTC',
    replayAt: '21:17 UTC',
    deadline: '22:00 UTC',
    replayWindowSec: 50 * 60,
    stages: [
      { id: 'upload', label: 'Upload', status: 'healthy', detail: 'Master received · 210 GB' },
      { id: 'ingest', label: 'Ingest', status: 'healthy', detail: 'Checksums verified' },
      { id: 'transcode', label: 'Transcode', status: 'healthy', detail: 'ABR ladders complete' },
      { id: 'subtitles', label: 'Subtitles', status: 'healthy', detail: '8 locales rendered' },
      { id: 'quality-control', label: 'Quality control', status: 'healthy', detail: 'Approved at 21:02 UTC' },
      { id: 'publish', label: 'Publish', status: 'failed', detail: 'CDN origin returning 5xx' },
    ],
    signals: [
      {
        id: 'origin-5xx',
        stage: 'publish',
        source: 'Prometheus',
        label: 'CDN origin 5xx rate',
        value: 41.8,
        unit: '%',
        baseline: 0.3,
        score: 100,
        finding: 'Two of five origin nodes are hard-down; the CDN fails 42% of segment fetches.',
        query: 'sum(rate(cineops_cdn_origin_5xx[5m])) / sum(rate(cineops_cdn_origin_requests[5m])) * 100',
      },
      {
        id: 'cache-hit',
        stage: 'publish',
        source: 'Prometheus',
        label: 'Cache hit ratio',
        value: 52.1,
        unit: '%',
        baseline: 94,
        score: 94,
        finding: 'Cache hit collapsed 42 points — viewers are hammering origins directly.',
        query: 'avg(cineops_cdn_cache_hit_percent)',
      },
      {
        id: 'origin-logs',
        stage: 'publish',
        source: 'Loki',
        label: 'Origin restart loop',
        value: 17.3,
        unit: '%',
        baseline: 0.2,
        score: 90,
        finding: 'Origin pods log OOMKilled restarts since the new season traffic spike.',
        query: '{service="cdn-origin"} |= "OOMKilled"',
      },
      {
        id: 'origin-latency',
        stage: 'publish',
        source: 'Prometheus',
        label: 'Origin response latency',
        value: 2.4,
        unit: 's',
        baseline: 0.18,
        score: 88,
        finding: 'Origin latency is 13× baseline as the surviving nodes absorb all traffic.',
        query: 'avg(cineops_cdn_origin_latency_seconds)',
      },
    ],
    toolCalls: [
      { tool: 'query_prometheus', purpose: 'Rank 5xx rate, cache hit, and latency' },
      { tool: 'query_loki_logs', purpose: 'Confirm origin OOM restart loop' },
      { tool: 'search_dashboards', purpose: 'Find CDN failover runbook' },
    ],
    playbooks: {
      publish: {
        decision: 'Origins are overloaded after the traffic spike. Fail over to the backup origin pool and raise memory limits before viewers notice buffering.',
        actions: [
          'Shift CDN origin traffic to the backup pool.',
          'Raise origin pod memory limits to stop the OOM restart loop.',
          'Purge hot segments so the cache rebuilds on the backup origins.',
        ]
      },
    },
  },
};
